
spring:
  main:
    allow-circular-references: true
  datasource:
    url:  jdbc:mysql://${MYSQL_HOST:localhost}:3308/readease_test
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql:true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: nlnktpm@gmail.com
    password: pkalikotmclhgbsh
    default-encoding: UTF-8
    properties:
      mail:
        mime:

          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080



#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/appchat
#spring.datasource.username=root
#spring.datasource.password=MySQL123
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true


#application.security.accessTokenSecret=very_long_and_very_secure_and_safe_access_token_key
#application.security.refreshTokenSecret=very_long_and_very_secure_and_safe_refresh_token_key
