server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  main:
    allow-circular-references: true
  datasource:
    url:  jdbc:mysql://${MYSQL_HOST:localhost}:3308/readease
    username: root
    password: root_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql:true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: readeaseapp@gmail.com
    password: ssamedljaceodrij
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8080

application:
  security:
    jwt:
      secret-key: 6a7d943fae1494133ebffb2bdf62ca3b83433052276bddd0cb27c380d0833e64
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
      expiration-reset-password: 3600000 # 1 hour
  cross-origin: http://localhost:3000 # front end
  drive-api:
    client-id: 726593784919-cqfv8c53np0li2n3d3eb3soens15ui0u.apps.googleusercontent.com
    client-secret: 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
# "https://read-ease.azurewebsites.net"



#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/appchat
#spring.datasource.username=root
#spring.datasource.password=MySQL123
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.properties.hibernate.format_sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true


#application.security.accessTokenSecret=very_long_and_very_secure_and_safe_access_token_key
#application.security.refreshTokenSecret=very_long_and_very_secure_and_safe_refresh_token_key
